### ISSUE TITLE
Crashes when using navigate-to from ED GUI

### ISSUE THREAD

**Issue by svddries** [tue-robotics/action_server#4]
[ERROR] [WallTime: 1424093351.038604] Error processing request: __init__() got an unexpected keyword argument 'designator'
['Traceback (most recent call last):\n', '  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 623, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/amigo/ros/hydro/system/src/action_server/src/action_server/main.py", line 198, in srv_add_action\n    server.add_action(req.action, config)\n', '  File "/home/amigo/ros/hydro/system/src/action_server/src/action_server/main.py", line 186, in add_action\n    self.action.create_action(action_type, config, self.robot)\n', '  File "/home/amigo/ros/hydro/system/src/action_server/src/action_server/main.py", line 154, in create_action\n    self.nwc = NavigateToObserve(robot, designator=Designator(self.goal_entity), radius=.5)\n', "TypeError: __init__() got an unexpected keyword argument 'designator'\n"]
[ERROR] [1424093351.039048166]: Service call failed: service [/action_server_py/add_action] responded with an error: error processing request: __init__() got an unexpected keyword argument 'designator'

**Comment by LoyVanBeek** [comment]
Maybe @Rayman can help with this one?

**Comment by Rayman** [comment]
I now get an other error:
```
[ERROR] [WallTime: 1427894619.367123] InvalidUserCodeError: Could not execute state 'GET_PLAN' of type '<robot_smach_states.navigation.navigation.getPlan object at 0x7f58d8014390>': Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 241, in _update_once
    self._remappings[self._current_label]))
  File "/home/ramon/ros/hydro/dev/src/robot_smach_states/src/robot_smach_states/navigation/navigation.py", line 71, in execute
    constraint = self.constraint_function()
  File "/home/ramon/ros/hydro/dev/src/robot_smach_states/src/robot_smach_states/navigation/navigate_to_observe.py", line 30, in generateConstraint
    e = self.entity_designator.resolve()
  File "/home/ramon/ros/hydro/dev/src/robot_smach_states/src/robot_smach_states/util/designators/designator.py", line 323, in resolve
    entities = self.ed.get_entities(_type, _center_point, self.radius, _id, self.parse)
  File "/home/ramon/ros/hydro/dev/src/robot_skills/src/robot_skills/world_model_ed.py", line 44, in get_entities
    center_point = self._transform_center_point_to_map(center_point)
  File "/home/ramon/ros/hydro/dev/src/robot_skills/src/robot_skills/world_model_ed.py", line 92, in _transform_center_point_to_map
    point_in_map = transformations.tf_transform(pointstamped.point, pointstamped.header.frame_id, "/map", self._tf_listener)
  File "/home/ramon/ros/hydro/dev/src/robot_skills/src/robot_skills/util/transformations.py", line 110, in tf_transform
    output_coordinates = tf_listener.transformPoint(outputframe, ps)
  File "/home/ramon/ros/hydro/system/src/tf_server/src/tf_server/tf_client.py", line 38, in transformPoint
    raise tf.Exception(resp.error_msg)
Exception: Invalid argument passed to lookupTransform argument source_frame in tf2 frame_ids cannot be empty
```

**Comment by LoyVanBeek** [comment]
Seems related to https://github.com/tue-robotics/robot_skills/issues/17 which i think I broke yesterday with the merge of https://github.com/tue-robotics/robot_smach_states/pull/29

**Comment by Rayman** [comment]
Now the action_server doesn't even startup...
```
Traceback (most recent call last):
  File "/home/amigo/ros/indigo/system/src/action_server/src/action_server/main.py", line 20, in <module>
    from robot_smach_states.util.designators import Designator, UnoccupiedArmDesignator, EdEntityDesignator, ArmHoldingEntityDesignator
ImportError: cannot import name UnoccupiedArmDesignator
```

**Comment by Rayman** [comment]
Probably fixed in 4c1bdd1caa616a5c3fb9e7a4a3650abd57b4b0a7
